services:
  chatgpt-telegram-workers:
    container_name: chatgpt-telegram-workers
    build: .
    image: chatgpt-telegram-workers:latest
    ports:
      - "${PORT:-8787}:${PORT:-8787}"
    environment:
      LOCAL_MODE: ${LOCAL_MODE:-webhook}
      PORT: ${PORT:-8787}
      TELEGRAM_AVAILABLE_TOKENS: ${TELEGRAM_AVAILABLE_TOKENS}
      OWNER_ID: ${OWNER_ID}
      REDIS_URL: ${REDIS_URL}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
